language: python
python:
  - "3.6"

install:
  - pip install --upgrade pip
  - pip install -U -r python/requirements.txt
  - python setup.py install

script:
  - pytest --cov=pygk --pep8

after_success:
  - coveralls